version: '3.9'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
      - DB_HOST=db
      - DB_USER=open-flights
      - DB_PASSWORD=mypassword
      - DB_NAME=open-flights_development
  db:
    image: postgres:14.1
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=open-flights
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=open-flights_development
