default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: myuser
  password: mypassword
  host: db
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>

development:
  <<: *default
  database: open-flights_development

test:
  <<: *default
  database: open-flights_test

production:
  <<: *default
  database: open-flights_production
  username: myuser
  password: mypassword
  host: db
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
