default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["POSTGRES_USER"] || 'open-flights' %>
  password: <%= ENV["POSTGRES_PASSWORD"] || 'mypassword' %>
  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>

development:
  <<: *default
  database: open-flights_development
